apiVersion: v2
name: paqtra
description: Paqtra — trace every flow. Network observability for Kubernetes
type: application
version: 2.2.1
appVersion: "2.2.1"
keywords:
  - cilium
  - network
  - observability
  - ebpf
  - kubernetes
maintainers:
  - name: Susant Sahani
home: https://github.com/zyvorai/paqtra
sources:
  - https://github.com/zyvorai/paqtra
