{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cilium-vision.fullname" . }}
  labels:
    {{- include "cilium-vision.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - namespaces
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["cilium.io"]
    resources:
      - ciliumnetworkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups: ["cilium.io"]
    resources:
      - ciliumendpoints
      - ciliumidentities
    verbs:
      - get
      - list
      - watch
  {{- with .Values.rbac.additionalRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cilium-vision.fullname" . }}
  labels:
    {{- include "cilium-vision.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cilium-vision.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cilium-vision.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
