{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cilium-vision.fullname" . }}-redis
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "cilium-vision.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "cilium-vision.redis.selectorLabels" . | nindent 4 }}
{{- end }}
