apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cilium-vision.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "cilium-vision.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.api.env.jwtSecret }}
  JWT_SECRET: {{ .Values.api.env.jwtSecret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
