apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cilium-vision.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "cilium-vision.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "cilium-vision.fullname" .))) -}}
  {{- if .Values.api.env.jwtSecret }}
  JWT_SECRET: {{ .Values.api.env.jwtSecret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ if $existingSecret }}{{ index $existingSecret.data "JWT_SECRET" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  {{- end }}
