apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: paqtra-api
  namespace: paqtra
spec:
  podSelector:
    matchLabels:
      app: paqtra-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: paqtra-ui
      ports:
        - port: 9191
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - port: 9191
