apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paqtra-api-pdb
  namespace: paqtra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paqtra-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paqtra-ui-pdb
  namespace: paqtra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paqtra-ui
